# Generated by Django 5.0.1 on 2024-02-13 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='custom_url',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Shortened'),
        ),
    ]
