# Generated by Django 5.0.1 on 2024-02-19 03:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_tracker', '0002_alter_url_custom_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='urltracker',
            name='url_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_url_tracker', to=settings.AUTH_USER_MODEL, verbose_name='URL Owner'),
        ),
    ]
